### PR TITLE
Refactor tests, add documentation and fix bugs

### LINKED ISSUE #18: `User` is a very common name for a public symbol
Perhaps this should be renamed to `WebAuthnUser`

### PR DESCRIPTION
**Pull request by marius-se**
This PR adds a lot of tests and test infrastructure.
Besides that I renamed some properties to follow the WebAuthn spec more closely, I renamed the `User` protocol to `WebAuthnUser`, which closes #18, and I updated the README a little bit.

Finally a lot of work went into adding attestation verification for packed and TPM attestation formats, but there are still too many pieces missing to release it. To fully support attestation verification we'll have to have support for:
- android key
- android safetynet
- apple
- fido u2f
- packed (95% done)
- tpm (70% done)

### CODE REVIEW

File: Tests/WebAuthnTests/WebAuthnManagerTests+Authentication.swift [hunk 1]
```diff
@@ -0,0 +1,188 @@
...
+//===----------------------------------------------------------------------===//
+
+@testable import WebAuthn
+import XCTest
+import SwiftCBOR
+import Crypto
+
+// swiftlint:disable line_length
+
+extension WebAuthnManagerTests {
```
Comment (0xTim) [inline Tests/WebAuthnTests/WebAuthnManagerTests+Authentication.swift:22]: We need to double check that these are picked up by test discovery on Linux because IIRC tests in extensions didn't used to be

File: Tests/WebAuthnTests/WebAuthnManagerTests+Authentication.swift [hunk 2]
```diff
@@ -0,0 +1,188 @@
...
+                    .validAuthenticationMock()
+                    .counter([0, 0, 0, 1]) // signCount = 1
+                    .buildAsBase64URLEncoded(),
+                credentialCurrentSignCount: 2
+            ),
+            expect: WebAuthnError.potentialReplayAttack
+        )
+    }
+// c155900296b95a46f75d57328e4523910e74d629331fcd12cce2e95644114182
+// cf28f38af10da2d9ca9e2d3bd373f0574253404075ca5d748869bbb01f8677be
```
Comment (0xTim) [inline Tests/WebAuthnTests/WebAuthnManagerTests+Authentication.swift:124]: What do these mean?

File: Tests/WebAuthnTests/WebAuthnManagerTests.swift [hunk 3]
```diff
@@ -17,42 +17,84 @@ import XCTest
...
+// swiftlint:disable identifier_name
 
 final class WebAuthnManagerTests: XCTestCase {
     var webAuthnManager: WebAuthnManager!
 
     let challenge: [UInt8] = [1, 0, 1]
     let relyingPartyDisplayName = "Testy test"
-    let relyingPartyID = "example.com"
+    let relyingPartyID = "webauthn.io"
     let relyingPartyOrigin = "https://example.com"
```
Comment (0xTim) [inline Tests/WebAuthnTests/WebAuthnManagerTests.swift:28]: Be good to have a comment as to why these are different

File: Tests/WebAuthnTests/WebAuthnManagerTests.swift [hunk 4]
```diff
@@ -345,20 +302,51 @@ final class WebAuthnManagerTests: XCTestCase {
...
+            .authData(authData)
+            .buildBase64URLEncoded()
+        let credential = try await finishRegistration(id: credentialID, attestationObject: attestationObject)
+        XCTAssertNotNil(credential)
+
+        XCTAssertEqual(credential.id, credentialID.asString())
+        XCTAssertEqual(credential.publicKey, credentialPublicKey)
+    }
+
+    // Swift CBOR library currently crashes when running this test. WE NEED TO FIX THIS
```
Comment (0xTim) [inline Tests/WebAuthnTests/WebAuthnManagerTests.swift:323]: Have we raised an issue on the library?

File: Tests/WebAuthnTests/WebAuthnManagerTests.swift [hunk 5]
```diff
@@ -345,20 +302,51 @@ final class WebAuthnManagerTests: XCTestCase {
...
+        clientDataJSON: URLEncodedBase64 = TestClientDataJSON().base64URLEncoded,
+        attestationObject: URLEncodedBase64 = TestAttestationObjectBuilder().validMock().buildBase64URLEncoded(),
         requireUserVerification: Bool = false,
         confirmCredentialIDNotRegisteredYet: (String) async throws -> Bool = { _ in true }
     ) async throws -> Credential {
         try await webAuthnManager.finishRegistration(
             challenge: challenge,
             credentialCreationData: RegistrationCredential(
-                id: id,
+                id: id.asString(),
```
Comment (0xTim) [inline Tests/WebAuthnTests/WebAuthnManagerTests.swift:349]: Is it worth extracting this to it's own type instead of just a `String`?

**Review by 0xTim — CHANGES_REQUESTED** [review]
Tests look way better! Added some comments and queries. Most changes are around documentation of public types

File: Sources/WebAuthn/Ceremonies/Registration/AttestationObject.swift [hunk 6]
```diff
@@ -39,14 +46,44 @@ public struct AttestationObject: Equatable {
...
+        //     )
+        // case .tpm:
+        //     try TPMAttestation.verify(
+        //         attStmt: attestationStatement,
+        //         authenticatorData: rawAuthenticatorData,
+        //         attestedCredentialData: attestedCredentialData,
+        //         clientDataHash: Data(clientDataHash),
+        //         credentialPublicKey: credentialPublicKey,
+        //         pemRootCertificates: pemRootCertificates
+        //     )
```
[the remark this answers is not in the document]
Comment (marius-se) [reply Sources/WebAuthn/Ceremonies/Registration/AttestationObject.swift:82]: We'll need this once attestation verification is ready. If uncommented it should compile, but the verification flow is not done yet.

File: Sources/WebAuthn/Ceremonies/Registration/PublicKeyCredentialCreationOptions.swift [hunk 7]
```diff
@@ -18,26 +18,28 @@ import Foundation
...
     public let timeout: TimeInterval
+    public let attestation: AttestationConveyancePreference
 }
 
 // MARK: - Credential parameters
 
 public struct PublicKeyCredentialParameters: Equatable, Codable {
     public let type: String
-    public let algorithm: COSEAlgorithmIdentifier
+    public let alg: COSEAlgorithmIdentifier
```
[the remark this answers is not in the document]
Comment (marius-se) [reply Sources/WebAuthn/Ceremonies/Registration/PublicKeyCredentialCreationOptions.swift:32]: Regular users of this library shouldn't care about this. They'll just encode this and send it to the frontend/ client without inspecting what's in there.

Internally following the naming conventions of the WebAuthn specs makes things a lot easier during development. But I'm happy to change it back since I know the codebase, I'm just worrying about newbies.

File: Tests/WebAuthnTests/WebAuthnManagerTests+Authentication.swift (hunk 2 above)
Comment (marius-se) [reply Tests/WebAuthnTests/WebAuthnManagerTests+Authentication.swift:124]: ah that's an artefact of debugging the signature verification :D Will remove that.

File: Tests/WebAuthnTests/WebAuthnManagerTests+Authentication.swift (hunk 1 above)
Comment (marius-se) [reply Tests/WebAuthnTests/WebAuthnManagerTests+Authentication.swift]: It did discover it on Linux, but I moved it to a separate class to keep the tests clean.

File: Tests/WebAuthnTests/WebAuthnManagerTests.swift (hunk 5 above)
Comment (marius-se) [reply Tests/WebAuthnTests/WebAuthnManagerTests.swift]: We're handling a lot of base64/base64url data and having some base64 "type safety" is super helpful.

File: Sources/WebAuthn/Ceremonies/Registration/PublicKeyCredentialCreationOptions.swift (hunk 7 above)
[the remark this answers is not in the document]
Comment (0xTim) [reply Sources/WebAuthn/Ceremonies/Registration/PublicKeyCredentialCreationOptions.swift:32]: Ok fair enough

**Review by 0xTim — APPROVED** [review]
Looks good!
